repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml # Check YAML files for syntax errors
    -   id: debug-statements # Check for debugger imports and py37+ breakpoint()
#    -   id: end-of-file-fixer # Ensure files end in a newline
#    -   id: trailing-whitespace # Trailing whitespace checker
    -   id: no-commit-to-branch # Prevent committing to main / master
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1
    hooks:
      - id: black
        args: [--line-length=120]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
